import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Location
 * Id: 882b0784-f08e-50ae-bdfb-2dfa9962a9d0
 * Codename: address
 */
export type Location = IContentItem<{
    /**
     * City (text)
     * Required: true
     * Id: f4197bc1-9cbe-5d4b-8c5c-70e50a2b41ff
     * Codename: city
     */
    city: Elements.TextElement;

    /**
     * Country (multiple_choice)
     * Required: true
     * Id: d6e5e429-7faf-5400-b61f-6dc7ed29a27c
     * Codename: country
     */
    country: Elements.MultipleChoiceElement;

    /**
     * Description (rich_text)
     * Required: false
     * Id: a1e55a73-b779-497c-acf1-ff4a82f57036
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 3a18e930-d3ad-4b13-ac14-1b7983c3dfee
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Latitude (text)
     * Required: false
     * Id: 12e96e3b-de85-5ceb-8225-ca76ceb0827e
     * Codename: latitude
     */
    latitude: Elements.TextElement;

    /**
     * Longitude (text)
     * Required: false
     * Id: eba52ef9-b87b-5899-8e10-e40623a6d4ce
     * Codename: longitude
     */
    longitude: Elements.TextElement;

    /**
     * Name (text)
     * Required: false
     * Id: ed1a5614-9ee0-4c89-ae41-cc6aefb99297
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * State (multiple_choice)
     * Required: false
     * Id: 50b9fa00-fcf1-5502-bbd4-de6c11ee3224
     * Codename: state
     */
    state: Elements.MultipleChoiceElement;

    /**
     * Street (text)
     * Required: true
     * Id: a93f3486-86db-5f2a-9c38-f284dcf70392
     * Codename: street
     */
    street: Elements.TextElement;

    /**
     * Suite (text)
     * Required: false
     * Id: cc2f87d8-8d54-5a36-b5e2-7596d8992e8d
     * Codename: suite
     */
    suite: Elements.TextElement;

    /**
     * Zip (text)
     * Required: false
     * Id: 163f920f-482f-5575-9b50-3da8e075101a
     * Codename: zip
     */
    zip: Elements.TextElement;
}>;
