import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Call to action
 * Id: 674ac807-5999-5b4e-814c-d5e59fa83da3
 * Codename: call_to_action
 */
export type CallToAction = IContentItem<{
    /**
     * Action Label (text)
     * Required: false
     * Id: 24ad2bf8-0c28-5f65-84ca-4fd11c6c4bb6
     * Codename: action_label
     */
    actionLabel: Elements.TextElement;

    /**
     * Action Type (multiple_choice)
     * Required: true
     * Id: 0606ad88-3c77-5172-a31d-cc4c75b26021
     * Codename: action_type
     */
    actionType: Elements.MultipleChoiceElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 9a5fa2d0-3b37-50a2-a3bd-2f1b2fd40869
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Link (text)
     * Required: false
     * Id: 66c5b163-5cfb-4e70-9188-7fd3a3f5fed9
     * Codename: link
     */
    link: Elements.TextElement;

    /**
     * Subtitle (text)
     * Required: false
     * Id: b4ff7692-642a-5ff1-a8d6-03f3bb29473a
     * Codename: subtitle
     */
    subtitle: Elements.TextElement;

    /**
     * Title (text)
     * Required: false
     * Id: c9d8d495-f9dc-5f7e-bcf9-e9969c7cac45
     * Codename: title
     */
    title: Elements.TextElement;
}>;
