import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Link } from './link.js';
import { type Metadata } from '../content-type-snippets/metadata.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Contact
 * Id: caf5447f-d85e-5116-b8bd-12d067ae9b51
 * Codename: location
 */
export type Contact = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: d7df0d79-5a71-504b-8c4c-d379afbfdd22
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Email (text)
     * Required: false
     * Id: 2deb4ed5-a2d3-553f-bee2-a8adbd0b4bfd
     * Codename: email
     */
    email: Elements.TextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: c327d598-0edf-5543-be67-c6a531b5f31b
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Name (text)
     * Required: true
     * Id: 98a6c7c2-dcbc-5eba-a5cc-c8cf9aa480b3
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Phone (text)
     * Required: false
     * Id: c9e83663-3b6d-5307-b706-b42eb755f391
     * Codename: phone
     */
    phone: Elements.TextElement;

    /**
     * Website (modular_content)
     * Required: false
     * Id: f947b05d-daa8-5c45-a680-1c2adedc0c43
     * Codename: website
     */
    website: Elements.LinkedItemsElement<Link>;
}> &
    Metadata;
