import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Contact } from './location.js';
import { type Link } from './link.js';
import { type Metadata } from '../content-type-snippets/metadata.js';
import { type OrganizationType } from '../taxonomies/organization_type.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Organization
 * Id: 27d710b3-8f38-5b65-b831-7df365d08749
 * Codename: organization
 */
export type Organization = IContentItem<{
    /**
     * Contact (modular_content)
     * Required: false
     * Id: b6af8be6-8120-5a71-b4f3-8ee1c101c793
     * Codename: contact
     */
    contact: Elements.LinkedItemsElement<Contact>;

    /**
     * Description (rich_text)
     * Required: false
     * Id: a6e7f0d9-58ab-56f7-a94b-43c6266ebeff
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: a6184dd4-8e84-556e-8c82-d85c590ec4b7
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Links (modular_content)
     * Required: false
     * Id: 54912382-17c5-58d6-b3a3-d3fb9df0cad2
     * Codename: links
     */
    links: Elements.LinkedItemsElement<Link>;

    /**
     * Name (text)
     * Required: true
     * Id: 7da5da6a-77f5-567a-9313-c593be252261
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Organization Type (taxonomy)
     * Required: false
     * Id: cfe0a19f-df1e-50c5-95e5-b97038c3ee4f
     * Codename: organization_type
     */
    organizationType: Elements.TaxonomyElement<OrganizationType>;
}> &
    Metadata;
