import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Metadata } from '../content-type-snippets/metadata.js';
import { type Persona } from '../taxonomies/persona.js';
import { type ProductType } from '../taxonomies/product_type.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Product
 * Id: 91ba5613-fbac-5d22-891a-eb9eadda5ea7
 * Codename: product
 */
export type Product = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: d873cef9-effb-5d0e-81bd-f424d43c4fec
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Image (asset)
     * Required: true
     * Id: 806d9bf8-94a5-5b6c-83de-a7d4a19b64ea
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Persona (taxonomy)
     * Required: false
     * Id: d7d829ae-7961-518d-90f1-f5129a412bc6
     * Codename: persona
     */
    persona: Elements.TaxonomyElement<Persona>;

    /**
     * Product Type (taxonomy)
     * Required: true
     * Id: be8af3b8-666f-58af-ab65-1ef9ca5ee2b9
     * Codename: product_type
     */
    productType: Elements.TaxonomyElement<ProductType>;

    /**
     * SKU (text)
     * Required: false
     * Id: 8ae2b936-f62e-5f9c-b8d1-d7266d59c981
     * Codename: sku
     *
     * If using text for a SKU, use a regular expression to match the expected SKU pattern.
     */
    sku: Elements.TextElement;

    /**
     * Slug (url_slug)
     * Required: false
     * Id: 81e05249-fd13-5cbf-a45b-f9e13586ba74
     * Codename: slug
     */
    slug: Elements.UrlSlugElement;

    /**
     * Title (text)
     * Required: true
     * Id: 3546fa85-6b13-56a4-9281-c9dfe2918f0e
     * Codename: title
     */
    title: Elements.TextElement;
}> &
    Metadata;
