import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Screen
 * Id: b2e3f1ab-79bf-4c65-afa2-541cac26883e
 * Codename: screen
 */
export type Screen = IContentItem<{
    /**
     * Content (modular_content)
     * Required: false
     * Id: 7e3f8034-3785-4827-86e2-f7b38792ff46
     * Codename: content
     */
    content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Subtitle (text)
     * Required: false
     * Id: 792663c5-2a1d-48af-814d-2cfd1803a6f8
     * Codename: subtitle
     */
    subtitle: Elements.TextElement;

    /**
     * Title (text)
     * Required: true
     * Id: 02bca171-7685-4568-893a-34ccdacc7fa4
     * Codename: title
     */
    title: Elements.TextElement;

       /**
     * Image (asset)
     * Required: false
     * Id: 
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Url Slug (url_slug)
     * Required: false
     * Id: a0543c1a-2ae8-40ce-bad8-9e8625050601
     * Codename: url_slug
     */
    urlSlug: Elements.UrlSlugElement;
}>;
