import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './person.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Testimonial
 * Id: a75b75ba-1e09-5846-9876-687d50890348
 * Codename: testimonial
 */
export type Testimonial = IContentItem<{
    /**
     * Person (modular_content)
     * Required: false
     * Id: 25c32e3e-ca36-5773-b633-3233a52dfc60
     * Codename: person
     */
    person: Elements.LinkedItemsElement<Person>;

    /**
     * Quote (rich_text)
     * Required: true
     * Id: 9d783451-f842-5a81-861a-e019796e104e
     * Codename: quote
     */
    quote: Elements.RichTextElement;
}>;
