import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Contact } from './location.js';
import { type Location } from './address.js';
import { type Metadata } from '../content-type-snippets/metadata.js';
import { type Organization } from './organization.js';
import { type TrainingType } from '../taxonomies/event_type.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Training
 * Id: 4672eebe-5609-57f3-a127-af6282241ab2
 * Codename: training
 */
export type Training = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: e542eeb4-fdbd-5f96-804e-6b25b348b713
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * End Date (date_time)
     * Required: false
     * Id: 0c10c9ee-e755-564d-a6a0-875a0305978d
     * Codename: end_date
     */
    endDate: Elements.DateTimeElement;

    /**
     * Training Type (taxonomy)
     * Required: true
     * Id: 942bbae5-8e45-55ac-9610-2698162db659
     * Codename: event_type
     */
    eventType: Elements.TaxonomyElement<TrainingType>;

    /**
     * Image (asset)
     * Required: false
     * Id: f5f03c8a-2557-5f8a-a546-6e56c0cc82b9
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Location (modular_content)
     * Required: false
     * Id: 057c3ec5-4a43-5b65-8f83-5abf15eaeab9
     * Codename: location
     */
    location: Elements.LinkedItemsElement<Contact | Location>;

    /**
     * Organizer (modular_content)
     * Required: false
     * Id: 38f48bcb-cce7-5165-9cbb-3a6d97e2f506
     * Codename: organizer
     */
    organizer: Elements.LinkedItemsElement<Organization>;

    /**
     * Slug (url_slug)
     * Required: false
     * Id: 65bf3809-c992-5d22-be35-0f49597aaa55
     * Codename: slug
     */
    slug: Elements.UrlSlugElement;

    /**
     * Start Date (date_time)
     * Required: true
     * Id: 9d9c9fe2-5b27-58b9-a012-5456ab3a4b52
     * Codename: start_date
     */
    startDate: Elements.DateTimeElement;

    /**
     * Title (text)
     * Required: false
     * Id: 9d6ad793-e84c-5268-b49c-d48fec0c090c
     * Codename: title
     */
    title: Elements.TextElement;
}> &
    Metadata;
