import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Metadata } from '../content-type-snippets/metadata.js';
import { type Persona } from '../taxonomies/persona.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Video
 * Id: 4117a0f4-6871-572e-b52f-c41bb54728de
 * Codename: video
 */
export type Video = IContentItem<{
    /**
     * Caption (text)
     * Required: false
     * Id: 0a55936a-dcff-59b3-ab4c-cb2bc097607b
     * Codename: caption
     */
    caption: Elements.TextElement;

    /**
     * Persona (taxonomy)
     * Required: false
     * Id: c2a9c385-affd-47ba-8247-16b1f525f1cb
     * Codename: persona
     */
    persona: Elements.TaxonomyElement<Persona>;

    /**
     * Title (text)
     * Required: false
     * Id: 822463c4-1f21-55f5-bd17-dbd01fa96118
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * Video Link (text)
     * Required: true
     * Id: 935cfa2e-fbed-4118-b245-2744df7e73ac
     * Codename: video_link
     */
    videoLink: Elements.TextElement;
}> &
    Metadata;
