/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Category
 * Id: 12014ef6-e28a-53d6-9e48-81595dee29c0
 * Codename: category
 */
export type Category =
    | 'electronics_and_computers'
    | 'fashion_and_accessories'
    | 'food_and_beverages'
    | 'home_and_garden'
    | 'sports_and_outdoors';
