/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Training Type
 * Id: 19d440db-94ee-5e5b-b823-1a4d366239a3
 * Codename: event_type
 */
export type TrainingType = 'conference' | 'fundraiser' | 'launch' | 'seminar' | 'training' | 'webinar';
