/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Organization Type
 * Id: 43ce5ad7-3cbb-5aca-a38c-610c6c580a2f
 * Codename: organization_type
 */
export type OrganizationType = 'manufacturer' | 'partner' | 'provider';
