/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Product Type
 * Id: 58d61f87-2149-552f-b73f-a909064cb859
 * Codename: product_type
 */
export type ProductType = 'consumable' | 'psc_motors';
