/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '52db433d-d6ef-49f5-a705-47f19f624a60',
        name: 'Project manager'
    }
} as const;
