/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const taxonomies = {
    /**
     * Category
     */
    category: {
        codename: 'category',
        id: '12014ef6-e28a-53d6-9e48-81595dee29c0',
        externalId: '6cdf48fc-caee-4f19-996c-03984d87061a',
        name: 'Category',
        terms: {
            electronics_and_computers: {
                codename: 'electronics_and_computers',
                id: 'b10706c0-4174-5326-96ed-3f125cf99d96',
                externalId: '16cad58c-d90a-4399-acb4-887394831bca',
                name: 'Electronics and Computers',
                terms: {}
            },
            fashion_and_accessories: {
                codename: 'fashion_and_accessories',
                id: '147895fd-7f2e-50cf-bd6f-0498c3f383cc',
                externalId: '9241d249-fb84-4b19-a276-d6b6b13055c3',
                name: 'Fashion and Accessories',
                terms: {}
            },
            food_and_beverages: {
                codename: 'food_and_beverages',
                id: '36b347ac-4c4b-58cc-a989-42f0f79d4798',
                externalId: 'f7143247-ad00-48d6-a5ec-6f31335ee104',
                name: 'Food and Beverages',
                terms: {}
            },
            home_and_garden: {
                codename: 'home_and_garden',
                id: 'be190801-1532-5be1-aaa6-d26d327c1df9',
                externalId: '041bed8d-088c-4b25-9e10-6bd4561843d3',
                name: 'Home and Garden',
                terms: {}
            },
            sports_and_outdoors: {
                codename: 'sports_and_outdoors',
                id: '7ab38eb3-8d0d-504d-bdc5-23b9ec3d9736',
                externalId: 'a2575e4d-f21a-4e62-801b-734ede50af1b',
                name: 'Sports and Outdoors',
                terms: {}
            }
        }
    },

    /**
     * Organization Type
     */
    organization_type: {
        codename: 'organization_type',
        id: '43ce5ad7-3cbb-5aca-a38c-610c6c580a2f',
        externalId: '719b6228-7a63-4248-88ab-7be1a45e9655',
        name: 'Organization Type',
        terms: {
            manufacturer: {
                codename: 'manufacturer',
                id: 'dae76dbf-0aa0-552b-a129-5c1dab23175b',
                externalId: 'e3a17d28-a6c6-4751-beaa-e22d47e95af6',
                name: 'Manufacturer',
                terms: {}
            },
            partner: {
                codename: 'partner',
                id: 'c83738ef-b0d7-5f6b-be3a-6a0689452431',
                externalId: '913f6617-272c-461b-85ac-c30dc8771a1c',
                name: 'Partner',
                terms: {}
            },
            provider: {
                codename: 'provider',
                id: 'f9aaacd7-c29c-5c82-8229-4f569ddf8be1',
                externalId: '478d585b-3113-4ab6-9796-03b75f6acd27',
                name: 'Provider',
                terms: {}
            }
        }
    },

    /**
     * Persona
     */
    persona: {
        codename: 'persona',
        id: '755c4200-8540-5920-9fe3-435699afbd61',
        externalId: '4a76a301-541a-4fc8-8809-e373d7bc7a0c',
        name: 'Persona',
        terms: {
            service_managers: {
                codename: 'service_managers',
                id: 'f5fb5603-5b45-4daa-8193-3d4de0ce22df',
                externalId: undefined,
                name: 'Service Managers',
                terms: {}
            },
            technicians: {
                codename: 'technicians',
                id: 'cb8a24bb-1d86-4401-adbb-55bac67be896',
                externalId: undefined,
                name: 'Technicians',
                terms: {}
            }
        }
    },

    /**
     * Product Type
     */
    product_type: {
        codename: 'product_type',
        id: '58d61f87-2149-552f-b73f-a909064cb859',
        externalId: '235d100a-def7-40d1-b270-8e6cee16edbf',
        name: 'Product Type',
        terms: {
            consumable: {
                codename: 'consumable',
                id: '2e90d45a-ddd8-5a05-9e14-f52f33fab64a',
                externalId: 'b204e803-3bf8-4a6d-aad7-7211242169ba',
                name: 'ECM Motors',
                terms: {}
            },
            psc_motors: {
                codename: 'psc_motors',
                id: '87c56e98-5ff4-4de0-a3b4-14307a178d47',
                externalId: undefined,
                name: 'PSC Motors',
                terms: {}
            }
        }
    },

    /**
     * Training Type
     */
    event_type: {
        codename: 'event_type',
        id: '19d440db-94ee-5e5b-b823-1a4d366239a3',
        externalId: 'b01bfbdc-0a4d-48fb-ae16-c35223641739',
        name: 'Training Type',
        terms: {
            conference: {
                codename: 'conference',
                id: 'eb750a10-eb9d-5d81-a13a-3b6073db8b77',
                externalId: 'ac34e8dd-f764-4e66-aeda-ea5b6f9f8464',
                name: 'Conference',
                terms: {}
            },
            fundraiser: {
                codename: 'fundraiser',
                id: 'a9dc19d8-2fa2-5e23-86aa-dbfedc5e0d1f',
                externalId: 'd6d801fb-fbb4-410e-9552-4e6224e3838b',
                name: 'Fundraiser',
                terms: {}
            },
            training: {
                codename: 'training',
                id: '66c44d40-8999-560d-90fe-783ef94d78ef',
                externalId: 'ce3e00e4-8d57-4183-9c33-2b4c3cfbb9bc',
                name: 'In-Class Training',
                terms: {}
            },
            launch: {
                codename: 'launch',
                id: 'e24632cc-3c9f-53b0-a018-c2db2a88f4c4',
                externalId: 'b82dd9a2-32be-4f25-b6eb-536352625d6a',
                name: 'Launch',
                terms: {}
            },
            seminar: {
                codename: 'seminar',
                id: '6ff722b6-f9af-5aaf-82eb-b0a4ee7ec426',
                externalId: '38895691-f36d-4091-beb9-6f28c8919661',
                name: 'Seminar',
                terms: {}
            },
            webinar: {
                codename: 'webinar',
                id: 'fda74b50-1bf0-5531-a217-dc161832c8d8',
                externalId: '6d5948d1-3588-4168-8b22-059657742bec',
                name: 'Webinar',
                terms: {}
            }
        }
    }
} as const;
