import Head from "next/head";
import Header from "../components/Header";
import Layout from "../components/Layout";
import Footer from "../components/Footer";
import { InferGetStaticPropsType, GetStaticProps } from 'next'
import { getItemByCodename, getItemsOfType } from "../services/kontentClient";
import { Screen } from "../models/content-types/screen";
import Testimonial from "../components/Testimonial";
import Video from "../components/Video";
import Product from "../components/Product";
import Training from "../components/Training";

export default function Home({screen,trainings}) {
  // const ctas = ;
  const products = screen.elements.content.linkedItems.filter(item => item.system.type =="product");
  const testimonials = screen.elements.content.linkedItems.filter(item => item.system.type =="testimonial");
  const videos = screen.elements.content.linkedItems.filter(item => item.system.type =="video");;

  return (
    <>
      <Head>
        <title>{screen.elements.title.value}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout screen={screen}/>
      {videos && videos.map(item =>(<Video video={item} key={item.system.id}/>))}
      {products && products.map(item =>(<Product product={item} key={item.system.id}/>))}
      {trainings && trainings.map(item =>(<Training training={item} key={item.system.id}/>))}
      {testimonials && testimonials.map(item =>(<Testimonial testimonial={item} key={item.system.id}/>))}
      <div className="w-full bg-emerald-700 h-32 text-right">
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const screen = await getItemByCodename<Screen>('universal_psc_and_ecm_landing', 5)
  const trainings = await getItemsOfType('training',3, 10)
  
  return {
    props: {
      screen,
      trainings
    },
  };
};


